from copy import deepcopy

from devotional_engine import EngineContext, MockAgentAdapter, State, run_engine
from tests.test_psalm42_integration import _psalm42_outputs


def _psalm43_outputs() -> dict:
    o = deepcopy(_psalm42_outputs())
    o["source_agent"] = {"source_text": "Psalm 43: Vindicate me, God, and plead my cause against an unfaithful nation. Rescue me from deceit and injustice. You are the God of my refuge. Why do I walk mourning under oppression? Send Your light and Your truth; let them lead me to Your holy mountain and dwelling. Then I will go to God's altar, to God my exceeding joy, and praise You with the lyre. Why are you bowed down, my living self? Wait for God, for I shall yet praise Him.", "chapter_verse_count": 5}
    o["translator"] = {"working_rendering": "Vindicate me, God, and contend for my cause. Rescue me from deceit and injustice. You are the God of my refuge. Why must I walk in mourning under oppression? Send Your light and Your truth; let them lead me to Your holy mountain and dwelling. Then I will come to God's altar, to God my exceeding joy, and praise You with the lyre. Why are you bowed down, my living self? Wait for God, for I shall yet praise Him."}
    o["chapter_design_mapper"] = {"chapter_start": "A worshiper asks God to judge his cause under deceit and oppression.", "chapter_end": "The bowed-down living self waits for future praise.", "emotional_movement": "Public injustice and mourning move through a plea for guidance toward altar, joy, and future praise.", "divine_action": "God vindicates, rescues, sends light and truth, leads to His dwelling, and remains the ground of praise.", "physical_vocabulary": ["walk", "mourning", "light", "truth", "lead", "mountain", "dwelling", "altar", "lyre"], "central_theological_claim": "The God of refuge answers oppression by judging truthfully and leading the worshiper back toward His presence.", "christward_fulfillment": "Jesus is the light and truth who brings His people to the Father.", "reader_felt_experience": "A person under false accusation keeps walking under pressure while asking God for a truthful path forward.", "chapter_design_summary": "The psalm moves from vindication to mourning, guided pilgrimage, altar joy, and future praise."}
    o["canonist"] = {"pathway": "Psalm 43 is not directly cited as prophecy. John 8:12 and John 14:6 provide a thematic correspondence: Christ is the light and truth who brings His people to the Father."}
    o["theological_risk_agent"] = {"risks": [{"risk_id": "R1", "risk_description": "Turn vindication into revenge.", "why_it_matters": "The worshiper places judgment with God.", "avoidance_rule": "Reject retaliation and preserve lawful protection.", "evaluator_check": "Application must not authorize revenge."}, {"risk_id": "R2", "risk_description": "Reduce light and truth to mood.", "why_it_matters": "They lead toward mountain, dwelling, altar, and praise.", "avoidance_rule": "Keep the images directional and worship-centered.", "evaluator_check": "Guidance must lead toward God."}]}
    o["historian_linguist"] = {"notes": "Light and truth are sent as guides toward God's holy dwelling."}
    o["commentary_agent"] = {"notes": "Psalm 43 shares Psalm 42's refrain but carries its own burden of vindication and guidance."}
    o["art_director"] = {"register": "restrained petition under public pressure", "pace": "judicial opening, embodied mourning, then forward movement toward worship", "sentence_music": "firm pleas opening into directional clauses", "image_density": "walking, light, road, mountain, dwelling, altar, lyre", "emotional_color": "grief becoming guided hope without premature triumph", "opening_mode": "embodied movement", "poem_tone": "common meter pilgrimage prayer", "ending_resonance": "the road toward the altar remains lit by promise", "avoid": ["revenge", "vague illumination", "instant resolution"]}
    o["creative_divergence_agent"] = {"threshold_phrase_candidates": ["Truth must lead somewhere.", "Send light for the next step.", "The road bends toward the altar.", "Mourning still has a direction.", "The judge's seat remains with God."], "introduction_opening_candidates": ["The worshiper is still walking.", "Oppression has changed his pace, not his direction.", "He asks for light because the road is not clear."], "governing_image_candidates": ["light falling across a pilgrim road", "truth leading uphill", "the altar heard before it is reached"], "christology_framing_candidates": ["Christ as light and truth who brings us to the Father", "Christ refusing revenge while entrusting judgment to the Father"], "poem_arc_candidates": ["dark road to holy mountain to altar song", "courtroom plea to guided road to exceeding joy"], "title_candidates": ["Light for the Road", "Led Toward the Altar", "When Truth Walks Ahead"], "epigraph_candidates": ["Truth must lead somewhere.", "The road bends toward the altar.", "Mourning still has a direction."]}
    o["director"] = {"chapter_burden": "The oppressed worshiper entrusts vindication to God and asks for light and truth to lead him toward God's presence.", "opening_movement": "a mourning worshiper keeps walking under oppression", "closing_movement": "light and truth lead toward altar, joy, and future praise", "central_thought": "The God of refuge answers oppression not by licensing revenge but by sending light and truth that lead the bowed-down worshiper toward His altar and future praise.", "emotional_charge": "grief earned through the gait of a person still walking under pressure", "transcendent_force": "God's light and truth moving as guides toward His dwelling", "selected_threshold_phrase": "Truth must lead somewhere.", "threshold_phrase_rationale": "The line preserves the psalm's directional logic.", "governing_image": "light falling across a pilgrim road", "image_lexicon": ["walk", "road", "light", "truth", "lead", "mountain", "dwelling", "altar", "lyre"], "image_head_terms": ["light", "road"], "anchor_terms": ["refuge", "light", "truth", "joy", "Christ"], "chapter_specific_terms": ["vindicate", "oppression", "light", "truth", "holy mountain", "altar", "exceeding joy"], "christology_required_echoes": ["light", "truth", "Christ", "Father"], "christology_pathway": "A thematic correspondence links God's sent light and truth with Christ, the light of the world and the truth who brings His people to the Father.", "application_target": "Entrust judgment to God, refuse revenge, ask for truthful guidance, and take the next faithful step toward worship.", "theological_terminus": "access to the Father through Christ, the true light and truth", "negative_constraints": ["emotion_earned_by_physical_fact", "no_unwarranted_deprivation", "do not endorse revenge", "do not reduce light to mood", "do not impose instant resolution"], "poem_plan": "common meter moving from a dark road to the holy mountain and altar praise", "semantic_proof_chain": ["vindicate", "refuge", "mourning", "light", "truth", "lead", "mountain", "altar", "joy", "praise"]}
    o["composer"] = {"title": "Light for the Road", "epigraph": "Truth must lead somewhere.", "focus_bible_verses": "Psalm 43:1-5 — Vindicate me, God. Send Your light and Your truth; let them lead me. Let them bring me to Your holy mountain and dwelling. Then I will go to God's altar, to God my exceeding joy.", "introduction": "Truth must lead somewhere.\n\nThe worshiper is still walking. Oppression has changed his pace, but not his direction. His steps carry the mourning before he names it. He asks God to judge his cause because he will not seize the judge's seat for himself.", "reflection": "Psalm 43 does not confuse vindication with revenge. The speaker names deceit, injustice, oppression, and the ache of feeling cast off, then places the case before God. His mourning has a gait: he walks under it. The body earns the sorrow before the psalm explains it. Then the prayer turns: Send Your light and Your truth. These are not decorative ideas or private moods. They are guides. They move ahead of the worshiper and bring him toward the mountain, the dwelling, the altar, and finally praise. The answer is not yet arrival. It is a trustworthy direction.", "christ_fulfillment": "Psalm 43 is not directly cited as a prophecy of Christ. Its strongest New Testament correspondence is thematic. Jesus names Himself the light of the world and the truth who brings His people to the Father. In Him, guidance is not detached information. Christ Himself becomes the way into God's presence. He does not authorize revenge against false accusers. He entrusts judgment to the Father and carries His people toward worship.", "application": "Place the case before God before rehearsing retaliation. Name the falsehood without becoming false. Ask what light Scripture gives for the next step and what truth must govern your speech. Then take one faithful step toward worship, counsel, reconciliation where possible, or lawful protection where necessary. Guidance is not always a full map. Often it is enough light to keep walking toward God.", "prayer": "Father, judge with righteousness where deceit and oppression have distorted what is true. Keep us from revenge and from becoming like those who wound us. Send Your light and Your truth to guide our next faithful step. Bring us through Christ to Your presence, restore truthful worship, and teach our bowed-down souls to wait for future praise, through Jesus Christ our Lord. Amen.", "next_in_sequence": "Psalm 44 - Faith remembers while defeat remains unexplained."}
    o["poet"] = {"poem": "Send light upon the road I tread,\nAnd truth to walk before;\nLead on toward Your holy hill,\nAnd bring me to Your door.\n\nI will not take the judge's chair\nNor answer wrong with wrong;\nYour altar waits beyond the dark,\nMy exceeding joy and song.\n\nThough sorrow slows my weary feet,\nYour promise still shall be\nA lamp that leads through Christ the Truth\nTo praise yet waiting me."}
    o["beauty_pass_agent"] = {"lingering_lines": ["The worshiper is still walking.", "The answer is not yet arrival. It is a trustworthy direction."], "strongest_turn": "Light and truth become guides rather than abstractions.", "weakest_artistic_moment": "", "mechanical_residue": [], "beauty_score": 9, "required_beauty_revisions": []}
    o["evaluator"] = {key: 9 for key in ["textual_fidelity", "theological_accuracy", "christology_from_chapter_logic", "chapter_design_fidelity", "emotional_charged_phrase", "introduction_strength", "ancient_image_discipline", "register", "read_aloud_quality", "application_concreteness", "prayer", "poem_form", "poetic_vitality", "artful_design", "artifact_integrity"]}
    o["evaluator"].update({"fault_target": "none", "notes": "Psalm 43 preserves vindication without revenge and keeps light and truth directional."})
    o["contradiction_editor"] = {"verdict": "Pass", "major_conflicts": [], "minor_conflicts": [], "theological_risks": [], "literary_risks": [], "harness_risks": [], "required_revisions": [], "notes": "No conflicts."}
    return o


def test_psalm43_runs_full_v64_pipeline_separately() -> None:
    ctx = run_engine(EngineContext(chapter_ref="Psalm 43"), MockAgentAdapter(_psalm43_outputs()))
    assert ctx.trace[-1] is State.DONE, ctx.error or ctx.failed_checks
    assert ctx.blueprint is not None and ctx.blueprint.approved
    assert ctx.trace.index(State.STORY_PLAN_BLUEPRINT) < ctx.trace.index(State.COMPOSE_PROSE)
    assert "revenge" in ctx.prose["reflection"].lower()
    assert "thematic" in ctx.prose["christ_fulfillment"].lower()
    assert "mourning has a gait" in ctx.prose["reflection"].lower()
    assert "Light for the Road" in ctx.artifact
