from enum import Enum, auto


class State(Enum):
    INIT = auto()
    SOURCE_TEXT = auto()
    RENDERING = auto()
    CHAPTER_DESIGN_MAP = auto()
    CANONICAL_CORRESPONDENCE = auto()
    THEOLOGICAL_RISK_REGISTER = auto()
    HISTORICAL_LINGUISTIC_CONTEXT = auto()
    COMMENTARY_GROUNDING = auto()
    ART_DIRECTION = auto()
    CREATIVE_DIVERGENCE = auto()
    DIRECTOR_BRIEF = auto()
    CHAPTER_ARC_GATE = auto()
    BRIEF_GATE = auto()
    COMPOSE_PROSE = auto()
    VOICE_REVIEW = auto()
    COMPOSE_POEM = auto()
    DETERMINISTIC_CHECK = auto()
    BEAUTY_PASS = auto()
    EVALUATE = auto()
    CONTRADICTION_EDITOR = auto()
    EDITORIAL_SMOOTHING = auto()
    POST_EDIT_VALIDATION = auto()
    LEDGER_UPDATE = auto()
    EMIT_ARTIFACT = auto()
    ESCALATED = auto()
    DONE = auto()
